apiVersion: extensions/v1beta1
kind: Job
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: miniosetup
  name: miniosetup
spec:
  replicas: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: miniosetup
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - ' sleep 10; /usr/bin/mc config host add myminio http://minio-service:9000 minio minio123; /usr/bin/mc mb myminio/state; /usr/bin/mc mb myminio/highavailability; exit 0; '
        image: minio/mc
        name: miniosetup
        resources: {}
      restartPolicy: OnFailure
status: {}
